### ISSUE TITLE
SketchfabApiConfigのCallback urlに適切なurlの入力方法がわかりません

### ISSUE THREAD

**Issue by r-sakakura** [curiosity-inc/sketchfab-unity#2]
堀川隆弘さん
素晴らしいコンテンツを作成していただきありがとうございます。

私はSampleSceneを実行してloginするときに必要なSketchfabApiConfigのCallback urlに適切なurlの入力方法がわかりません。
SketchfabApiConfigにはclient idとCallback urlが必要なので[開発者向けsketchfabログイン](https://sketchfab.com/developers/oauth)を参考にアプリ登録を行いました。

登録内容は下記の通りです。
Application name : sketchfab-unity
Grant type : Authorization Code
Redirect URI : http://[localhost]:[port number]/
Your Sketchfab username : [Sketchfab username]
Tell us a bit more about your app: 
Is it for downloading or uploading?:  downloading

登録後sketchfabからclient id と redirect urlを提供されたのでSketchfabApiConfigに入力して実行しloginを押しましたが、画面遷移先でこのサイトにアクセスできませんと表示されます。
想定としては画面遷移後Unityに戻ることが正しいと思われますが、登録したRedirect URlが適切ではないためこのような挙動になったと思います。
アプリ登録の際に設定するRedirect URlはどのように設定すればよろしいでしょうか？
Unityバージョンは2019.4.19f1です。

**Comment by thorikawa** [comment]
Redirect URIはご自身の管理されているドメインのURLであれば何でも問題ありません。

ただし、Redirectされた後、Redirect URIによってUnityアプリケーションに自動で戻るためには、
ビルドプラットフォームごとにdeeplinkの設定が必要になります。
https://docs.unity3d.com/ja/2019.4/Manual/enabling-deep-linking.html

たとえばiOSでは、Appleが提供するUniversal Linkという仕組みによってdeeplinkを実現しており、
Redirect URIに設定したサーバーにapple-app-site-associationというファイルを配置したり
xcodeのビルド設定でcapabilitiesを設定したりする必要があります。
以下の例のように詳細を説明しているブログがいくつか検索できると思いますのでそちらを参照してください。
https://qiita.com/mono0926/items/2bf651246714f20df626

時間ができたら、これらの情報を含め詳細をREADMEに記載するつもりでいます。
